version: "3.9"

services:
  backend:
    build: ./ecommerce-server
    container_name: ecommerce-backend
    ports:
      - "5454:5454"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=ecommerce
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      - db
    networks:
      - ecommerce-net

  frontend:
    build: ./react
    container_name: ecommerce-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - ecommerce-net

  db:
    image: mysql:8.0
    container_name: ecommerce-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ecommerce-net

volumes:
  db_data:

networks:
  ecommerce-net:
    driver: bridge
